### ISSUE TITLE
Error getting Simple Text Classifier model up

### ISSUE THREAD

**Issue by DeStiNi10** [heartexlabs/label-studio-ml-backend#23] opened 2021-06-01 07:06 UTC
on running `label-studio-ml init my_ml_backend --script label_studio_ml/examples/simple_text_classifier.py`

I get 

`Can't import module "simple_text_classifier", reason: No module named 'core'.
If you are looking for examples, you can find a dummy model.py here:
https://labelstud.io/tutorials/dummy_model.html`

and on running `label-studio-ml start my_ml_backend`

I get 

`python: can't open file './my_ml_backend/_wsgi.py': [Errno 2] No such file or directory`

Is this an expected behaviour?

**Comment by KonstantinKorotaev** [comment] 2021-07-23 14:55
Hi DeStiNi10 

Could you please clarify what OS you are using?

Did you install requirements from the repository root folder (label-studio-ml-backend)?

**Comment by makseq** [comment] 2021-07-23 20:07
@DeStiNi10

**Comment by KonstantinKorotaev** [comment] 2021-10-01 16:55
@DeStiNi10 the issue is fixed in master by [PR](https://github.com/heartexlabs/label-studio-ml-backend/pull/43)

**Closed** 2021-10-01 16:55 UTC
